class_path: pytorch_lightning.trainer.trainer.Trainer
init_args:
  accelerator: gpu
  devices: [0]
  accumulate_grad_batches: 2
  benchmark: null
  check_val_every_n_epoch: 1
  default_root_dir: null
  deterministic: True
  fast_dev_run: False
  max_epochs: 1
  min_epochs: 1
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  overfit_batches: 0
  val_check_interval: 1.0
  num_sanity_val_steps: 10
  log_every_n_steps: 50
  enable_progress_bar: true
  enable_model_summary: true
  gradient_clip_val: 1.0
  gradient_clip_algorithm: norm
  inference_mode: true
  profiler: null
  detect_anomaly: false
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
